### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by nrenner** [Turistforeningen/leaflet-routing#1]
Is there a public demo available?
If not, do you happen to know which public (OSM) routing service would fit in without much modifications?

**Comment by Starefossen** [comment]
Due to some copyright limitation imposed on our data source I am not able to provide a live demo, yet. Almost any service would fit - it only needs to support a LatLng start and a LatLng stop and return a Linestring. We use pgRouting (Postgres postgis built in function).

I will post more technical info as soon as I am back at work over the weeked.

**Comment by nrenner** [comment]
Thanks, that will do for the moment. I'll give it a try and probably come back with some questions.

**Comment by Starefossen** [comment]
![Leaflet Routing Demo](https://raw.github.com/Turistforeningen/leaflet-routing/gh-pages/images/promo.gif)

**Comment by nrenner** [comment]
Nice! I was looking at using an OpenStreetMap based service for an online demo, but either the API is not public, requires a key or is too complicated for a simple demo. Best option seems to be YOURS, but that does not support CORS or JSONP - still want to try that with a proxy and/or create a feature request.

OT: I actually started integrating Leaflet.routing into a web client for an offline router, but that needs some more work. Great to see deleting waypoints and leftover trailing lines fixed!

**Comment by Starefossen** [comment]
Looking forward to hear how the integration goes! Do not hesitate to create new issues if you find bugs and need some new feature.

**Comment by nrenner** [comment]
I added a first version of an OpenStreetMap based [online demo](http://nrenner.github.io/leaflet-routing/#http://norbertrenner.de/proxycors.php?url=) to my gh-pages branch. It currently requires a remote proxy (passed as hash) for requests to [yournavigation.org](http://yournavigation.org/) and does not support snapping yet (might add a static file).

**Comment by Starefossen** [comment]
That is so sweet @nrenner! Do you mind if I add a link to it from the readme file?

**Comment by nrenner** [comment]
No, go ahead. It might be an issue though that the data of this routing service is a bit outdated, so not all ways on the map are routable or match up. Don't know if there will be an update anytime soon, otherwise we could choose a different area where all ways have been added earlier.

**Comment by nrenner** [comment]
I moved the demo to a [gist](https://gist.github.com/nrenner/8566972) because it got me into trouble with upstream merges into my gh-pages branch. So here is the [new demo link](http://bl.ocks.org/nrenner/raw/8566972/#http://norbertrenner.de/proxycors.php?url=).

**Comment by Starefossen** [comment]
Thank you so much @nrenner. I used some of your work to make a demo for Leaflet.Routing. It is here: http://turistforeningen.github.io/leaflet-routing/examples/osm.html.

**Comment by nrenner** [comment]
Nice, glad I could help a bit with that. Saw you added it to the plugins list, was going to suggest.
