### ISSUE TITLE
About custom waypoints and routing

### ISSUE THREAD

**Issue by ghost** [Turistforeningen/leaflet-routing#26]
Hi,

I got 20 points of a way and i want to use my way data on map. But i couldnt figure out of it. I got an array which has lat & long values. I can create geojson but in your example i couldnt understand the third value: etc

[8.90724154784554,61.4991902326406,1136],       this is your data, and what does 1136 means?
thank you

**Comment by Starefossen** [comment]
Hi @navinova,

The third value is an optional value according to the GeoJSON specification. In this case it represents `altitude` (height above sea level). We use this value to create a graph to show users how steep the accent/decent is.

**Comment by ghost** [comment]
Hi Starefossen,

Thank you for your kind reply. I still trying to do sth with your lib. i got custom data (lat &lon points). Is there any way to do routing with this points? 

If you give me any advice, i would be grateful, thanks

**Comment by Starefossen** [comment]
Yes, you can use this library with only lon,lat coordinates. You should take a look at [this example](https://github.com/Turistforeningen/leaflet-routing/blob/gh-pages/examples/osm.html#L110) (more specifically the custom routing function) for how to use this library.
