### ISSUE TITLE
Init routing

### ISSUE THREAD

**Issue by jeroenbourgois** [Turistforeningen/leaflet-routing#28]
Hi

I am struggling to use your lib. I am using the `L.Control.Geocoder` control by Per Liedman which gives me LatLong coords for two points. How can I then trigger the routing function? I search around the web for an example combining leaflet + routing, but I find it really hard to find. Also: I am specifically looking for bike routes, so OSRM is not an option at the moment.

**Comment by Starefossen** [comment]
Hi @jeroenbourgois,

Not sure if you managed to solve your problem but I'm going to reply anyway. 

If you look at the router in the [OSM example](https://github.com/Turistforeningen/leaflet-routing/blob/gh-pages/examples/osm.html#L110) is what you need to modify. This function is triggered when the user is interacting with Leaflet.Routing. It has the two points as first and second argument and a callback function as a third.

Replace the body of the `route` function with calls to the `L.Control.Geocoder` and return the result to the `cb` function.

Just ask if anything is unclear :)

**Comment by jeroenbourgois** [comment]
Ok, thank you!
