### ISSUE TITLE
OSM router not respond

### ISSUE THREAD

**Issue by Nefedov89** [Turistforeningen/leaflet-routing#29]
Hi. Help me please with problem 
I try to draw route, but it dont work because my 'build-route url' http://www2.turistforeningen.no/routing.php?url=http://www.yournavigation.org/api/1.0/gosmore.php&format=geojson&v=foot&fast=1&layer=mapnik&flat=51.48182022464805&flon=-0.16329678241163492&tlat=51.58262629388259
not respond and i can not create route.

Also I try demo http://turistforeningen.github.io/leaflet-routing/examples/osm.html and it does not work too

As I understood this routing service is unavailable now. Can I replace it by any other routing service?

**Comment by Starefossen** [comment]
Yes, it seems like the routing service we are relying on [yournavigation.org](http://downforeveryoneorjustme.com/yournavigation.org) is down. Hopefully it will be back soon.

I don't known any other open routing services you can use in the mean time.

**Comment by nrenner** [comment]
For a little more info regarding yournavigation.org see [OSM Forum](http://forum.openstreetmap.org/viewtopic.php?pid=459634#p459634).

Alternatives for integration might be:
- [Mapzen instance](https://mapzen.com/blog/osrm-services) of [OSRM](http://wiki.openstreetmap.org/wiki/Open_Source_Routing_Machine)
- [Directions API](http://developer.mapquest.com/web/products/open/directions-service) by [MapQuest Open](http://open.mapquest.com/)

See also [Routing](http://wiki.openstreetmap.org/wiki/Routing) at OSM Wiki.

**Comment by Starefossen** [comment]
Thanks for the heads up @nrenner. I will try to find another router for the demo if yournavigation.org is down for a long time.

**Comment by Nefedov89** [comment]
Hi again. Obviously http://www.yournavigation.org work fine now ( http://forum.openstreetmap.org/viewtopic.php?pid=461984#p461984 ), but I can not still draw my route and demo not work for me. Can you check this issue?

Best regards

**Comment by Starefossen** [comment]
Unfortunately the API from yournavigation.org is not fully working yet. Look at what it returns:

``` json
{
  "type": "LineString",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "coordinates":
  [
[8.629732, 61.491066]
,[8.629711, 61.491066]
...
,[8.719095, 61.501805]
,[8.720230, 61.501884]
  ],  "properties": {
    "distance": "6.640379",
    "description": "To enable simple instructions add: 'instructions=1' as parameter to the URL",
    "traveltime": "4812"
    }
}
<br />
<b>Warning</b>:  fopen(/home/lambertus/public_html/yours/cache-20141110.csv): failed to open stream: No such file or directory in <b>/var/www/api/1.0/gosmore.php</b> on line <b>382</b><br />
<br />
<b>Warning</b>:  fopen(/home/lambertus/public_html/yours/cache-20141110.csv): failed to open stream: No such file or directory in <b>/var/www/api/1.0/gosmore.php</b> on line <b>389</b><br />
```

The HTML at the end is not valid JSON and thus the JSON parsing fails.
