### ISSUE TITLE
User Specified Routing Service

### ISSUE THREAD

**Issue by canadaka** [Turistforeningen/leaflet-routing#32]
Is there any info about how one creates a routing service?
You seem to run your own "/route/?" what did you use to create this?
I see many OSM based routing projects here
http://wiki.openstreetmap.org/wiki/Routing

I'm new to routing and trying to figure out how I might be able to do routing on a database of linestring in a Postgres database. I can convert them to OSM if need be.

**Comment by Starefossen** [comment]
Hi @canadaka,

The example uses the OSM router from http://www.yournavigation.org, there are some other OSM routers as mentioned in [this comment](https://github.com/Turistforeningen/leaflet-routing/issues/29#issuecomment-62057400).

If you have your own Postgres database you should check out the [pgRouting project](http://pgrouting.org), we use that internally here at the Norwegian Trekking Association.
