### ISSUE TITLE
Use L.Polyline for snapping layer?

### ISSUE THREAD

**Issue by canadaka** [Turistforeningen/leaflet-routing#33]
In your example you use some proxy to load .OSM data for the snapping layer.

Is it possible to use Polylines already drawn on the leaflet map for the snapping layer?

**Comment by Starefossen** [comment]
Hi @canadaka,

The snapping can work on any layer of Polylines, just point Leaflet Routing to the correct layer when you instantiate it and it should work ok:

``` javascript
var routing = new L.Routing({
  …,
  snapping: {
    layers: [myPolylineLayer]
  }
});
```

**Comment by canadaka** [comment]
Oh OK cool, I guess this doesn't work with encodedPath's though?
https://github.com/jieter/Leaflet.encoded

**Comment by Starefossen** [comment]
No, they have to be L.Polyline in an L.Layer. So you have to decode them and add them to your snapping layer like this:

``` javascript
var snapping_layer = new L.LayerGroup();

for (var i = 0; i < encoded_polylines.length; i++) {
  L.Polyline.fromEncoded(encoded_polylines[i]).addTo(snapping_layer);
}
```

**Comment by canadaka** [comment]
Thanks that was helpful, got it working. But FYI for anyone else there is no "new L.Layer();" method, use "new L.LayerGroup();"
