### ISSUE TITLE
API auth failed

### ISSUE THREAD

**Issue by bado57** [Turistforeningen/leaflet-routing#38]
Uncaught Error: API auth failed app.js:21. Thanks a lot great example.

**Comment by Starefossen** [comment]
Ahh.. Sorry for the confusion. That is an old demo, you should stick with the one in the `example` directory. They should all be working.

**Comment by bado57** [comment]
Hi dear. I search all of leaflet examples. I want to this sample install in my server and I want to use that like restfull api. So I want to take request and get response. How can I do that . Can you help me about this situation. Have nice night.
