### ISSUE TITLE
how to add my own  router background ？

### ISSUE THREAD

**Issue by qxang** [Turistforeningen/leaflet-routing#39]
my router can only be the geojson？

**Comment by Starefossen** [comment]
Do you want to do client side (in the browser) routing on GeoJSON?

**Comment by qxang** [comment]
Hi,it is. I want to do client side. Is it ok?

**Comment by Starefossen** [comment]
No, this library requires a an external routing service. You should take a look at https://github.com/perliedman/geojson-path-finder or try to implement one yourself :)

**Comment by qxang** [comment]
Ok,thank you.
