### ISSUE TITLE
route update event/callback

### ISSUE THREAD

**Issue by nrenner** [Turistforeningen/leaflet-routing#5]
A client needs some way to get informed after the route has been updated in order to update route statistics like track length or an elevation diagram. Hooking into the router callback only gives you the updated segments and I find it easier to always work with the complete route.

Possible solutions could be:
a) fire an update event in routeWaypoint before cb is called
b) an option to pass a callback that is used instead of the debug callbacks passed e.g. from L.Routing.Draw._onMouseClick

I can provide a PR for that. What are your thoughts/preferences?

**Comment by Starefossen** [comment]
I completely agree with you, working with a complete route is the best. I think solution a) would be the nicest way to implement this.

Any suggestion for naming conventions? Leaflet.draw has `draw:created`, `draw:edited`, and so on. Should we stick with this schema?
- `routing:preRouteWaypoint` // called before routing starts
- `routing:postRouteWaypoint` // called after routing but before callback

What do you think?

**Comment by nrenner** [comment]
I'm bad at naming. I simply used `routing:update` in my prototype, but specific pre/post events for routeWaypoint are more flexible. When fired from the L.Routing instance instead of map the prefix might not be needed, but I would add it anyway. 

Leaflet seems to use start/end instead of pre/post, e.g. movestart/moveend, dragstart/dragend, so what about (no strong opinion about that)
- `routing:routeWaypointStart`
- `routing:routeWaypointEnd`

**Comment by Starefossen** [comment]
Go for it @nrenner. Just make a PR and I'll be sure to merge it in :)
